build_image:
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t registry.gitlab.com/mind21/ghcr_test .
    - docker push registry.gitlab.com/mind21/ghcr_test